// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjhcmkevxhldcpvqkshe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqaGNta2V2eGhsZGNwdnFrc2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjk1OTksImV4cCI6MjA1NTk0NTU5OX0.b96mUFeDqBlLa53LCqO_7mbGb9lZvQPO4lDjFLo1sPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);